SELECT COD_CONTRATO, DATA, TOTAL
FROM TCONTRATO
WHERE TOTAL >
  (SELECT VALOR FROM TCURSO WHERE COD_CURSO = 1);

  --Errado (só pode retornar 1
  --linha na cunsulta)
SELECT COD_CONTRATO, DATA, TOTAL
FROM TCONTRATO
WHERE TOTAL >=
  (SELECT VALOR FROM TCURSO
   WHERE VALOR > 500);

--Todos os Alunos da mesma cidade do aluno 1
--menos o aluno 1
SELECT COD_ALUNO, NOME, CIDADE
FROM TALUNO
WHERE CIDADE = (SELECT CIDADE FROM TALUNO
      WHERE COD_ALUNO = 1
      AND COD_ALUNO <>1);

SELECT * FROM TALUNO;

--soma todos os itens, e mostra somente
-- valor mínimo seja maior que o valor
-- dos cursos
SELECT COD_CUSOM, Min(VALOR) Sum(VALOR)
Count(*) QTDE
FROM TITEM
WHERE COD_CURSO > 0
GROUP BY COD_CURSO
HAVING Min(VALOR) >=
  SELECT Avg(VALOR) FROM TCURSO)
ORDER BY COD_CURSO;

-- Soma o total de contrato por aluno e mostra somente
-- cujo menor contrato seja maio que
-- o valor medio de curso
SELECT COD_ALUNO, Min(TOTAL), Sum(TOTAL)
FROM TCONTRATO
GROUP BY COD_ALUNO
HAVING Min(TOTAL) >
  (SELECT Avg(VALOR) FROM TCURSO);

--todos os cursos que estao na tabela de
--item vendidos
SELECT COD_CURSO, NOME, VALOR
FROM TCURSO
WHERE COD_CURSO IN (SELECT COD_CURSO FROM TITEM);

--TODOS OS CURSOS QUE NAO ESTAO NA TABELA ITEM NAO VENDIDOS
SELECT COD_CURSO, NOME, VALOR
FROM TCURSO
WHERE COD_CURSO NOT IN (SELECT COD_CURSO FROM TITEM)
ORDER BY NOME;

--CODIGO EQUIVALENTE A SUBSELECT
-- SE OS VALORES SAO CONHECIDOS
SELECT COD_CURSO, NOME, VALOR
FROM TCURSO WHERE COD_CURSO IN (1,2,3,4);

SELECT COD_CURSO, NOME, VALOR
FROM TCURSO
WHERE COD_CURSO = 1
OR COD_CURSO = 2
OR COD_CURSO = 3
OR COD_CURSO = 4;

--TODOS CURSOS QUE FORAM VENDIDOS
-- PELO VALOR PADRAO
SELECT * FROM TITEM
WHERE(COD_CURSO, VALOR) IN (SELECT COD_CURSO, VALOR FROM TCURSO);


--SUBCONSULTAS NA CLAUSULA FROM
SELECT ITE.COD_CONTRATO, ITE.VALOR,
       ITE.COD_CURSO,
       CUR.COD_CURSO, CUR.VALOR
FROM TITEM ITE,
      (SELECT COD_CURSO, VALOR
        FROM TCURSO WHERE VALOR > 500) CUR
WHERE CUR.COD_CURSO = ITE.COD_CURSO;













