
SELECT Count(*) AS QTDE_REGISTROS,
              Avg(TOTAL) AS MEDIA,
              Round(Avg(TOTAL),2) AS MEDIA,
              Max(TOTAL) AS MAXIMO,
              Min(TOTAL) AS MINIMO,
              Sum(TOTAL) AS SOMA,
              Max(DATA) AS DATA_MAIOR,
              Min(DATA) AS DATA_MENOR FROM TCONTRATO;

SELECT Max(COD_CONTRATO) + 1 AS PROXIMO_CODIGO FROM TCONTRATO;

SELECT * FROM TALUNO;
SELECT * FROM TCONTRATO;

--TOTAL DE CONTRATOS POR ALUNO
SELECT COD_ALUNO,
Count(*) AS QTDE_CONTRATO,
Sum(TOTAL) AS VALOR_TOTAL FROM TCONTRATO
GROUP BY COD_ALUNO;

--TOTAL DE CONTRATO POR DATA
SELECT To_Char(Trunc(DATA), 'DD/MM/YYYY') AS DATA,
        Sum(TOTAL) AS SOMA,
        Avg(TOTAL) AS MEDIA,
        Count(*) AS QTDE
FROM TCONTRATO
GROUP BY Trunc(DATA)
ORDER BY DATA DESC;

COMMIT;

UPDATE TCONTRATO SET
  DESCONTO = NULL
WHERE COD_CONTRATO = 4;

UPDATE TCONTRATO SET
  DESCONTO = NULL
WHERE COD_CONTRATO = 3;

SELECT Count(*) AS QTDE_REGISTROS
FROM TCONTRATO;

SELECT * FROM TCONTRATO;

--COUNT -> IGNORA NULOS
SELECT Count(DESCONTO)
FROM TCONTRATO;

--qtde de registros com estado informado
SELECT Count(ESTADO) FROM TALUNO;

--qtde de registros por estados
SELECT ESTADO, Count(*) FROM TALUNO GROUP BY ESTADO;

--
SELECT Sum(DESCONTO),
       Avg(DESCONTO),
       Count(DESCONTO),
       Round(Avg(Nvl(DESCONTO,0)), 2)
FROM TCONTRATO;


SELECT * FROM TCONTRATO;

SELECT ALU.ESTADO, Sum(CON.TOTAL) AS TOTAL, Count(*) QTDE
FROM TALUNO ALU, TCONTRATO CON
WHERE ALU.COD_ALUNO = CON.COD_ALUNO
GROUP BY ALU.ESTADO
ORDER BY ALU.ESTADO;

SELECT COD_ALUNO, Avg(TOTAL) MEDIA
FROM TCONTRATO
WHERE COD_ALUNO > 0
HAVING Avg(TOTAL) > 500
GROUP BY COD_ALUNO
ORDER BY COD_ALUNO;

SELECT Trunc(DATA), Sum(TOTAL) TOTAL
FROM TCONTRATO
WHERE COD_ALUNO > 0
GROUP BY Trunc(DATA)
HAVING Sum(TOTAL) > 500
ORDER BY TOTAL DESC;

--media mais alta por aluno
SELECT Max(Avg(TOTAL))
FROM TCONTRATO
GROUP BY COD_ALUNO;

--soma dos salarios por estado
SELECT ESTADO, Sum(SALARIO) AS TOTAL
FROM TALUNO
GROUP BY ESTADO
ORDER BY 2 DESC;


