
 CREATE SEQUENCE SEQ_ALUNO1
 START WITH 60 --VALOR INICIAL
 INCREMENT BY 5 --QTDE A INCREMENTAR
 MINVALUE 60 --VALOR MINIMO
 MAXVALUE 250 --VALOR MAXIMO
 NOCACHE --NAO GUARDA EM CACHE FAIXA DE VALORES
 NOCYCLE;

INSERT INTO TALUNO (Cod_Aluno, Nome)
VALUES (SEQ_ALUNO1.NEXTVAL, 'MASTER TRAINING 2');

 SELECT * FROM TALUNO;
 COMMIT;

 SELECT * FROM USER_SEQUENCES;

 SELECT SEQ_ALUNO1.CURRVAL FROM DUAL;

 ALTER SEQUENCE SEQ_ALUNO1
 MAXVALUE 500;

--Indices secundario
SELECT NOME FROM TALUNO
WHERE NOME LIKE '%A%';  --f9 faz um plano de execução

CREATE INDEX IND_TALUNO_NOME1 ON TALUNO(NOME);

SELECT NOME FROM TALUNO
WHERE NOME LIKE '%MA%';

CREATE INDEX IND_TALU_NOMECIDADE
ON TALUNO(NOME, CIDADE);

SELECT NOME FROM TALUNO
WHERE NOME LIKE '%MA%' AND CIDADE LIKE '%A%';

SELECT * FROM USER_INDEXES;

DROP INDEX IND_TALU_NOMECIDADE;

--SINONIMOS
CREATE SYNONYM ALU FOR TALUNO;

SELECT * FROM ALU;




